config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  
  devise_for :admins, skip: %i[registrations passwords], controllers: {
  sessions: "admin/sessions"
  }
  
  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  
  # ゲストユーザーログイン用ルート
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admin/sessions#admin_guest_sign_in'
  end
  
  scope module: :public do
    resources :gyms, only:%i[index show] do
      resource :favorite_gyms, only: %i[create destroy] 
    end
    get 'users/:id', to: 'users#show', as: 'user'
    get 'user/profile', to:'users#edit'
    patch 'user/update', to:'users#update'
    get 'user/confirm', to:'users#confirm'
    patch 'user/hide', to:'users#hide'
    resources :users, only: %i[] do
      resource :relationships, only: %i[create destroy]
      # ルート要編集
      get 'favorite_gyms', to:'favorite_gyms#index'
      get "followings", to: 'relationships#followings'
      get "followers", to: 'relationships#followers'
    end
    resources :training_records, only:%i[new show create destroy] do
      resources :post_comments, only: %i[create destroy]
      resource :likes, only: %i[create destroy]
    end
    get "search", to:"training_records#search"
  end
  
  namespace :admin do
    get 'top', to:'homes#top'
    resources :users, only:%i[index show update]
    resources :training_records, only:%i[show edit update]
    resources :gyms, only:%i[new create index show edit update]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # ゲストログイン用メソッド
  def self.admin_guest
    find_or_create_by!(email: 'admin_guest@example.com') do |admin|
      admin.password = SecureRandom.urlsafe_base64
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/detail.rb
class Detail < ApplicationRecord
  
  with_options numericality: { greater_than_or_equal_to: 1 }, presence: true do
    validates :weight
    validates :rep
    validates :set
  end
  
  
  belongs_to :menu
  belongs_to :training_record
end

app/models/favorite_gym.rb
class FavoriteGym < ApplicationRecord
  belongs_to :user
  belongs_to :gym

  validates :user_id, uniqueness: {scope: :gym_id}
end

app/models/gym.rb
class Gym < ApplicationRecord
  has_many :users
  # タイムラインでジムの投稿一覧を表示させるため
  has_many :training_records, through: :users
  has_many :favorite_gyms, dependent: :destroy
  has_many :favorited_users, through: :favorite_gyms, source: :user
  
  with_options presence: true do
    validates :gym_name
    validates :postcode
    validates :address
    validates :fee
    validates :is_open
  end
  
  def favorited_by?(user)
    favorite_gyms.exists?(user_id: user.id)
  end
  
    # ransackに検索を許可するリストを設定
  def self.ransackable_attributes(auth_object = nil)
      ["gym_name"]
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :training_record
  
  validates :user_id, uniqueness: {scope: :training_record_id}
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :details
  accepts_nested_attributes_for :details, allow_destroy: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :training_record
  
  validates :comment, presence: true, length: {maximum: 25}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :training_record
end

app/models/training_record.rb
class TrainingRecord < ApplicationRecord
  # 詳細のアソシエーション、ネスト
  has_many :details, inverse_of: :training_record, dependent: :destroy
  accepts_nested_attributes_for :details, reject_if: :all_blank, allow_destroy: true

  belongs_to :user
  # タイムラインでジムの投稿一覧を表示させるため
  has_one :master,  through: :user
  has_many :post_comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  
  has_many :tags, dependent: :destroy
  
  has_one_attached :image


  validates :content, length: {maximum: 150}
  # コメントだけの投稿も許可する
  # validates :details, presence: true

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

  # ransackに検索を許可するリストを設定
def self.ransackable_attributes(auth_object = nil)
    ["content", "user_id"]
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "Guest"
      user.gym_id = "1"
      user.is_active = true
    end
  end       
  
  # ログイン時の会員ステータス確認
  def active_for_authentication?
    super && (self.is_active == true)
  end
  
  # フォロー機能
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_users, through: :followers, source: :followed
  has_many :follower_users, through: :followeds, source: :follower
  # 登録ジムとお気に入りジム
  belongs_to :gym
  has_many :favorite_gyms, dependent: :destroy
  has_many :favorited_gyms, through: :favorite_gyms, source: :gym
  # トレーニング記録
  has_many :training_records, dependent: :destroy
  accepts_nested_attributes_for :training_records, allow_destroy: true
  # コメント
  has_many :post_comments, dependent: :destroy
  # いいね
  has_many :likes, dependent: :destroy
  has_many :liked_training_records, through: :likes, source: :training_record

  validates :description, length: {maximum: 160}
  validates :name,presence: true

  has_one_attached :profile_image
  # プロフィール画像取得
  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
  end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # フォロー確認
  def following?(user)
    following_users.include?(user)
  end

  # ransackに検索を許可するリストを設定
  def self.ransackable_attributes(auth_object = nil)
      ["name"]
  end

end

app/controllers/admin/gyms_controller.rb
class Admin::GymsController < ApplicationController

  def new
    @gym = Gym.new
  end

  def index
    @gyms = Gym.all
  end

  def create
    @gym = Gym.new(gym_params)
    if @gym.save
      redirect_to admin_gyms_path
    else
       render :new
    end
  end

  def edit
    @gym = Gym.find(params[:id])
  end

  def update
    @gym = Gym.find(params[:id])
    if @gym.update(gym_params)
      redirect_to admin_gyms_path
    else
      render :edit
    end
  end

  def destroy
    @gym = Gym.find(params[:id])
    @gym.destroy
    redirect_to admin_gyms_path
  end

  private

  def gym_params
    params.require(:gym).permit(:gym_name, :postcode, :address, :fee, :is_open)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
  
  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gym_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!

  def top
    @training_records = current_user.gym.training_records.all
    @follower_training_records = TrainingRecord.where(user_id: [current_user.id, *current_user.following_users])
  end
end

app/helpers/admin/gyms_helper.rb
module Admin::GymsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/training_records_helper.rb
module TrainingRecordsHelper
end

app/helpers/user/post_comments_helper.rb
module User::PostCommentsHelper
end

app/views/admin/gyms/edit.html.erb
<h1>ジム編集</h1>

<!--エラーテンプレート-->
<div id="comments_error">
  <%= render 'layouts/errors', model: @gym %>
</div>

<%= form_with model: @gym, url: admin_gym_path, method: :patch, local: true  do |f| %>
  <div class="edit_item">ジム名</div>
    <%= f.text_field :gym_name, placeholder:@gym.gym_name %>
  <div class="edit_item">郵便番号</div>
    <%= f.text_field :postcode, placeholder:@gym.postcode %>
  <div class="edit_item">住所</div>
    <%= f.text_area :address, placeholder:@gym.address, style: "width:300px" %>
  <div class="edit_item">月額</div>
    <%= f.text_field :fee, placeholder:@gym.fee %>
  <div>
    <%= f.radio_button :is_open, :true %>
    <%= f.label :is_open_true,"営業中", style: "margin-top: 20px;" %>
  </div>
  <div>
    <%= f.radio_button :is_open, :false %>
    <%= f.label :is_open_false,"閉店" %>
  </div>
  <br>
  <%= f.submit "保存", class: 'link update_btn' %>
<% end %>

app/views/admin/gyms/index.html.erb
<%= link_to "新しく作成する", new_admin_gym_path, method: :get, class: "btn btn-secondary" %>

<table class="table">
  <thead>
    <tr>
      <th>店舗名</th>
      <th>郵便番号</th>
      <th>住所</th>
      <th>月額</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @gyms.each do |gym| %>
    <tr>
      <td><%= gym.gym_name %></td>
      <td><%= gym.postcode %></td>
      <td><%= gym.address %></td>
      <td>￥<%= gym.fee.to_s(:delimited) %></td>
      <td><%= link_to "編集する", edit_admin_gym_path(gym), method: :get, class: "btn btn-outline-secondary" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/gyms/new.html.erb
<h1>ジム新規登録</h1>

<!--エラーテンプレート-->
<div id="comments_error">
  <%= render 'layouts/errors', model: @gym %>
</div>

<%= form_with model: @gym, url: admin_gyms_path, method: :post, local: true  do |f| %>
  <div class="edit_item">ジム名</div>
    <%= f.text_field :gym_name, placeholder:"ジム名" %>
  <div class="edit_item">郵便番号</div>
    <%= f.text_field :postcode, placeholder:"0000000" %>
  <div class="edit_item">住所</div>
    <%= f.text_area :address, placeholder:"住所", style: "width:300px" %>
  <div class="edit_item">月額</div>
    <%= f.text_field :fee, placeholder:"例：7000" %>
  <div>
    <%= f.radio_button :is_open, :true %>
    <%= f.label :is_open_true,"営業中", style: "margin-top: 20px;" %>
  </div>
  <div>
    <%= f.radio_button :is_open, :false %>
    <%= f.label :is_open_false,"閉店" %>
  </div>
  <br>
  <%= f.submit "保存", class: 'link update_btn' %>
<% end %>