config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  
  devise_for :admins, skip: %i[registrations passwords], controllers: {
  sessions: "admin/sessions"
  }
  
  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  
  # ゲストユーザーログイン用ルート
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admin/sessions#admin_guest_sign_in'
  end
  
  scope module: :public do
    resources :gyms, only:%i[index show] do
      resource :favorite_gyms, only: %i[create destroy] 
    end
    get 'users/:id', to: 'users#show', as: 'user'
    get 'user/profile', to:'users#edit'
    patch 'user/update', to:'users#update'
    get 'user/confirm', to:'users#confirm'
    patch 'user/hide', to:'users#hide'
    resources :users, only: %i[] do
      resource :relationships, only: %i[create destroy]
      # ルート要編集
      get 'favorite_gyms', to:'favorite_gyms#index'
      get "followings", to: 'relationships#followings'
      get "followers", to: 'relationships#followers'
    end
    resources :training_records, only:%i[new show create destroy] do
      resources :post_comments, only: %i[create destroy]
      resource :likes, only: %i[create destroy]
    end
    get "search", to:"training_records#search"
  end
  
  namespace :admin do
    get 'top', to:'homes#top'
    resources :users, only:%i[index show update]
    resources :training_records, only:%i[show edit update]
    resources :gyms, only:%i[new create index show edit update]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "Guest"
      user.gym_id = "1"
      user.is_active = true
    end
  end       
  
  # ログイン時の会員ステータス確認
  def active_for_authentication?
    super && (self.is_active == true)
  end
  
  # フォロー機能
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_users, through: :followers, source: :followed
  has_many :follower_users, through: :followeds, source: :follower
  # 登録ジムとお気に入りジム
  belongs_to :gym
  has_many :favorite_gyms, dependent: :destroy
  has_many :favorited_gyms, through: :favorite_gyms, source: :gym
  # トレーニング記録
  has_many :training_records, dependent: :destroy
  accepts_nested_attributes_for :training_records, allow_destroy: true
  # コメント
  has_many :post_comments, dependent: :destroy
  # いいね
  has_many :likes, dependent: :destroy
  has_many :liked_training_records, through: :likes, source: :training_record

  validates :description, length: {maximum: 160}
  validates :name,presence: true

  has_one_attached :profile_image
  # プロフィール画像取得
  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
  end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # フォロー確認
  def following?(user)
    following_users.include?(user)
  end

  # ransackに検索を許可するリストを設定
  def self.ransackable_attributes(auth_object = nil)
      ["name"]
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @training_records = @user.training_records
    @users_gym = @user.gym
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
  end
  
  
  private

  def user_params
    params.require(:user).permit(:is_active)
  end
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/user/post_comments_helper.rb
module User::PostCommentsHelper
end

app/views/admin/users/_active_btn.html.erb
<% if user.is_active %>
  <p>
    <%= link_to "退会させる", admin_user_path(user, user: { is_active: !user.is_active }), method: :patch, remote: true, data: {"turbolinks" => false} , class: "btn btn-danger" %>
  </p>
  <% else %>
  <p>
    <%= link_to "復活させる", admin_user_path(user, user: { is_active: !user.is_active }), method: :patch, remote: true, data: {"turbolinks" => false} , class: "btn btn-primary" %>
  </p>
<% end %>

app/views/admin/users/index.html.erb
<% @users.each do |user| %>
  <div class="user_index">
    <div class="user_index_user">
      <%= link_to admin_user_path(user), method: :get, class: "link user_index_user" do %>
        <div class="image_tag"><%= image_tag user.get_profile_image(80,80), class: "rounded-circle", size: "80x80"  %></div>
        <div class="timeline_users_name"><strong><%= user.name%></strong></div>
        <!--<div class="user_index_user_description"><%= user.description%></div>-->
        <div class="user_index_user_gym">登録ジム：<%= user.gym.gym_name%></div>
      <% end %>
      <!--非同期のためのid設定-->
        <div id="active_btn_<%= user.id %>", style="margin-left: auto;">
          <%= render '/admin/users/active_btn', user: user %>
        </div>
    </div>
  </div>
<% end %>

app/views/admin/users/show.html.erb
<div class="show_profile">
  <div class="profile_head">
    <%= image_tag @user.get_profile_image(150,150), class: "rounded-circle", size: "150x150"  %>
    <div class="user_follow_info">
      <div class="user_follow_info_item">
        <%= @user.training_records.count %>投稿
      </div>
      <div class="user_follow_info_item">  
        <%= @user.followers.count %>フォロー
      </div>
      <div class="user_follow_info_item">  
        <%= @user.followeds.count %>フォロワー
      </div>
      <div class="user_follow_info_item">  
        <%= @user.favorite_gyms.count %>お気に入りジム
      </div>
    </div>
  </div>
  <div class="user_info">
    <div class="user_name"><strong><%= @user.name%></strong></div>
    <div class="show_user_description" style="white-space:pre-wrap;" ><%= @user.description%></div>
    <div class="show_user_gym">登録ジム：<%= @users_gym.gym_name%></div>
  </div>
</div>

<%= render '/admin/training_records/timeline', training_records: @training_records %>

app/views/admin/users/update.js.erb
$("#active_btn_<%= @user.id %>").html("<%= j(render '/admin/users/active_btn', user: @user) %>");