config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  
  devise_for :admins, skip: %i[registrations passwords], controllers: {
  sessions: "admin/sessions"
  }
  
  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  
  # ゲストユーザーログイン用ルート
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admin/sessions#admin_guest_sign_in'
  end
  
  scope module: :public do
    resources :gyms, only:%i[index show] do
      resource :favorite_gyms, only: %i[create destroy] 
    end
    get 'users/:id', to: 'users#show', as: 'user'
    get 'user/profile', to:'users#edit'
    patch 'user/update', to:'users#update'
    get 'user/confirm', to:'users#confirm'
    patch 'user/hide', to:'users#hide'
    resources :users, only: %i[] do
      resource :relationships, only: %i[create destroy]
      # ルート要編集
      get 'favorite_gyms', to:'favorite_gyms#index'
      get "followings", to: 'relationships#followings'
      get "followers", to: 'relationships#followers'
    end
    resources :training_records, only:%i[new show create destroy] do
      resources :post_comments, only: %i[create destroy]
      resource :likes, only: %i[create destroy]
    end
    get "search", to:"training_records#search"
  end
  
  namespace :admin do
    get 'top', to:'homes#top'
    resources :users, only:%i[index show update]
    resources :training_records, only:%i[show edit update]
    resources :gyms, only:%i[new create index show edit update]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # ゲストログイン用メソッド
  def self.admin_guest
    find_or_create_by!(email: 'admin_guest@example.com') do |admin|
      admin.password = SecureRandom.urlsafe_base64
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/detail.rb
class Detail < ApplicationRecord
  
  with_options numericality: { greater_than_or_equal_to: 1 }, presence: true do
    validates :weight
    validates :rep
    validates :set
  end
  
  
  belongs_to :menu
  belongs_to :training_record
end

app/models/favorite_gym.rb
class FavoriteGym < ApplicationRecord
  belongs_to :user
  belongs_to :gym

  validates :user_id, uniqueness: {scope: :gym_id}
end

app/models/gym.rb
class Gym < ApplicationRecord
  has_many :users
  # タイムラインでジムの投稿一覧を表示させるため
  has_many :training_records, through: :users
  has_many :favorite_gyms, dependent: :destroy
  has_many :favorited_users, through: :favorite_gyms, source: :user
  
  with_options presence: true do
    validates :gym_name
    validates :postcode
    validates :address
    validates :fee
    validates :is_open
  end
  
  def favorited_by?(user)
    favorite_gyms.exists?(user_id: user.id)
  end
  
    # ransackに検索を許可するリストを設定
  def self.ransackable_attributes(auth_object = nil)
      ["gym_name"]
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :training_record
  
  validates :user_id, uniqueness: {scope: :training_record_id}
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :details
  accepts_nested_attributes_for :details, allow_destroy: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :training_record
  
  validates :comment, presence: true, length: {maximum: 25}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :training_record
end

app/models/training_record.rb
class TrainingRecord < ApplicationRecord
  # 詳細のアソシエーション、ネスト
  has_many :details, inverse_of: :training_record, dependent: :destroy
  accepts_nested_attributes_for :details, reject_if: :all_blank, allow_destroy: true

  belongs_to :user
  # タイムラインでジムの投稿一覧を表示させるため
  has_one :master,  through: :user
  has_many :post_comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  
  has_many :tags, dependent: :destroy
  
  has_one_attached :image


  validates :content, length: {maximum: 150}
  # コメントだけの投稿も許可する
  # validates :details, presence: true

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

  # ransackに検索を許可するリストを設定
def self.ransackable_attributes(auth_object = nil)
    ["content", "user_id"]
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "Guest"
      user.gym_id = "1"
      user.is_active = true
    end
  end       
  
  # ログイン時の会員ステータス確認
  def active_for_authentication?
    super && (self.is_active == true)
  end
  
  # フォロー機能
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_users, through: :followers, source: :followed
  has_many :follower_users, through: :followeds, source: :follower
  # 登録ジムとお気に入りジム
  belongs_to :gym
  has_many :favorite_gyms, dependent: :destroy
  has_many :favorited_gyms, through: :favorite_gyms, source: :gym
  # トレーニング記録
  has_many :training_records, dependent: :destroy
  accepts_nested_attributes_for :training_records, allow_destroy: true
  # コメント
  has_many :post_comments, dependent: :destroy
  # いいね
  has_many :likes, dependent: :destroy
  has_many :liked_training_records, through: :likes, source: :training_record

  validates :description, length: {maximum: 160}
  validates :name,presence: true

  has_one_attached :profile_image
  # プロフィール画像取得
  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
  end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # フォロー確認
  def following?(user)
    following_users.include?(user)
  end

  # ransackに検索を許可するリストを設定
  def self.ransackable_attributes(auth_object = nil)
      ["name"]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
  
  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gym_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!

  def top
    @training_records = current_user.gym.training_records.all
    @follower_training_records = TrainingRecord.where(user_id: [current_user.id, *current_user.following_users])
  end
end

app/helpers/admin/gyms_helper.rb
module Admin::GymsHelper
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/training_records_helper.rb
module TrainingRecordsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
  <!--エラー表示-->
  <% if model.errors.any? %>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end%>
    </ul>
  <% end %>

app/views/layouts/_search.html.erb
<div class="search_form">
  <!--複数モデルから検索したい場合ransack「search_from_forヘルパー」ではなく通常の「form_with」でコントローラーに検ワードを送った方がよさそう。-->
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :q, placeholder: "投稿orユーザー検索", class: 'search_field' %>
  <% f.submit "検索" %>
<% end %>
</div>

app/views/layouts/_timeline.html.erb
<% training_records.each do |training_record| %>
  <div class="timeline">
    <div class="timeline_user">
      <%= link_to user_path(training_record.user), method: :get, class: "link timeline_user_link" do %>
        <div class="image_tag"><%= image_tag training_record.user.get_profile_image(50,50), class: "rounded-circle", size: "50x50"  %></div>
        <div class="timeline_users_name"><strong><%= training_record.user.name%></strong></div>
      <% end %>
      <div class="date"><%= training_record.created_at.strftime('%Y/%m/%d') %></div>
    </div>
    <%= link_to training_record_path(training_record.id), class: "link" do %>
    <!--"white-space:pre-wrap;"＝改行表示-->
      <div class="content" style="white-space:pre-wrap;" >
        <%= training_record.content %>
      </div>
      <% training_record.details.each do |detail| %>
        <div class="detail">
          <p><%= detail.menu.name %></p>
          <p><%= detail.weight %>kg</p>
          <p><%= detail.rep %>回</p>
          <p><%= detail.set %>セット</p>
        </div>
      <% end %>
      <div class="timeline_info">
        <!--非同期のためのid設定-->
        <div id="like_buttons_<%= training_record.id %>">
          <%= render '/public/likes/like_btn', training_record: training_record %>
        </div>
        <%= link_to training_record_path(training_record.id), class: "link" do %>
          <i class="far fa-comment"></i><%= training_record.post_comments.count %>
        <% end %>
        <% if training_record.user == current_user %>
          <%= link_to training_record_path(training_record), data: { confirm: '本当に消しますか？' },  method: :delete, class: "link training_record_delete" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Joytore</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/15ed15601f.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body>
    <header>
      <div class="header">
        
        <% if admin_signed_in?%> 
          <%= link_to admin_top_path, class: "header_name" do %>
             <%= image_tag asset_path('joytore_logo.png'), style: "width: 200px;" %> 
          <% end %>
        <% else %>
          <%= link_to root_path, class: "header_name" do %>
            <%= image_tag asset_path('joytore_logo.png'), style: "width: 200px;" %>
          <% end %>
        <% end %>
      </div>
    </header>
        <% if user_signed_in? %>
          <%= render '/layouts/search' %>
        <% end %>
        
    <% flash.each do |message_type, message| %>
      <div style="color: red;">
        <%= message %>
      </div>
    <% end %>

    <div class="main">
      <% if user_signed_in? %>
        <div class="sideber">
          <%= render '/public/users/side_ber', user: current_user %>
        </div>
      <% end %>
      <div class="main_content">
        <%= yield %>
      </div>
      <% if admin_signed_in?%> 
        <div class="left_sideber"></div>
      <% end %>
    </div>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <time datetime="<%= start_date.strftime('%Y-%m') %>" class="calendar-title"><%= start_date.year %><%= t('date.month_names')[start_date.month] %> </time>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title">
      <%= t('simple_calendar.week', default: 'Week') %>
      <%= calendar.week_number %>
      <% if calendar.number_of_weeks > 1 %>
        - <%= calendar.end_week %>
      <% end %>
    </span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>